# Generated by Django 4.1.7 on 2023-04-03 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data_cadastro', models.DateField(verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=250, null=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('editora', models.CharField(max_length=100, null=True, verbose_name='Editora')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='Status')),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagens', verbose_name='Imagem')),
                ('data_cadastro', models.DateField(verbose_name='Data de cadastro')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='emprestimos.autor', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('data_emprestimo', models.DateField(verbose_name='Data de emprestimo')),
                ('data_devolucao', models.DateField(verbose_name='Data de devolução')),
                ('devolucao', models.BooleanField(verbose_name='Devolvido')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='emprestimos.autor', verbose_name='Autor')),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='livros_emprestimo', to='emprestimos.livro', verbose_name='livro')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
    ]
